# Generated by Django 3.1.4 on 2021-05-18 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cummunities', '0002_auto_20210519_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(default=[], null=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='posts',
            field=models.ManyToManyField(default=[], null=True, related_name='community_posts', to='cummunities.Post'),
        ),
    ]
