# Generated by Django 3.1.4 on 2021-05-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cummunities', '0003_auto_20210519_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(default=[], null=True, to='cummunities.Comment'),
        ),
    ]
