# Generated by Django 3.1.4 on 2020-12-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_discoverbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title_name',
            field=models.CharField(default='No Title', max_length=264),
        ),
        migrations.AlterField(
            model_name='discoverbookmark',
            name='title_name',
            field=models.CharField(default='No Title', max_length=264),
        ),
    ]
