# Generated by Django 3.1.4 on 2020-12-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='timeline',
            name='bookmark',
            field=models.ManyToManyField(null=True, to='home.Bookmark'),
        ),
    ]
