# Generated by Django 3.1.4 on 2020-12-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201218_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='bookmark',
            new_name='bookmarks',
        ),
    ]
