# Generated by Django 3.1.4 on 2020-12-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201219_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='bookmarks',
            field=models.ManyToManyField(to='home.Bookmark'),
        ),
    ]
