# Generated by Django 3.1.4 on 2020-12-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201215_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoverbookmark',
            name='slug',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url_field',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='discoverbookmark',
            name='url_field',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('title_name', 'url_field')},
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='slug',
        ),
    ]
