# Generated by Django 3.1.4 on 2020-12-15 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201215_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url_field',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='discoverbookmark',
            name='url_field',
            field=models.URLField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
    ]
