# Generated by Django 3.1.4 on 2020-12-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_discoverbookmark_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='discoverbookmark',
            name='slug',
        ),
        migrations.AlterField(
            model_name='discoverbookmark',
            name='url_field',
            field=models.URLField(),
        ),
    ]
