# Generated by Django 3.1.4 on 2020-12-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201209_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.CharField(default='No Description', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='image_field',
            field=models.URLField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title_name',
            field=models.CharField(default='No Title', max_length=264, unique=True),
        ),
    ]
