# Generated by Django 3.1.4 on 2020-12-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201214_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title_name',
            field=models.CharField(default='No Title', max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='discoverbookmark',
            name='title_name',
            field=models.CharField(default='No Title', max_length=264, unique=True),
        ),
    ]
