# Generated by Django 3.1.4 on 2020-12-15 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201215_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverbookmark',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
