# Generated by Django 3.1.1 on 2021-01-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201216_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url_field',
            field=models.URLField(),
        ),
    ]
