# Generated by Django 3.1.1 on 2021-01-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210104_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url_field',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='discoverbookmark',
            name='url_field',
            field=models.URLField(unique=True),
        ),
    ]
