# Generated by Django 3.1.4 on 2021-05-18 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarksection', '0002_auto_20210519_0030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hentaimelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='bookmarks',
            field=models.ManyToManyField(default=[], to='bookmarksection.Bookmark'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
